apiVersion: v1
kind: Service
metadata:
  name: mailhog-web
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  namespace: crapi
spec:
  ports:
  - name: web
    port: 8025
    nodePort: 30025
    protocol: TCP
  selector:
    app: mailhog
  sessionAffinity: None
  type: LoadBalancer
