apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailhog-web
  namespace: crapi
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  labels:
    app: crapi-web
spec:
  rules:
  - host: mailhog-web.9fb2d620bbe449fc880a.southcentralus.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mailhog-web
            port:
              number: 80

# apiVersion: v1
# kind: Service
# metadata:
#   name: mailhog-web
#   annotations:
#     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
#   namespace: crapi
# spec:
#   ports:
#   - name: web
#     port: 8025
#     nodePort: 30025
#     protocol: TCP
#   selector:
#     app: mailhog
#   sessionAffinity: None
#   type: LoadBalancer
