apiVersion: v1
kind: Service
metadata:
  name: crapi-web
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: crapi-web
spec:
  ports:
  - port: 80
    nodePort: 30080
    name: nginx
  type: LoadBalancer
  selector:
    app: crapi-web
