apiVersion: v1
kind: Service
metadata:
  name: crapi-web
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  labels:
    app: crapi-web
spec:
  rules:
  - host: crapi-web.crapi-dns-2b952e50.hcp.southcentralus.azmk8s.io
    http:
      paths:
      - backend:
          serviceName: crapi-web
          servicePort: 80
          
 # ports:
 #  - port: 80
 #    nodePort: 30080
 #  selector:
 #    app: crapi-web
