apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crapi-web
  namespace: crapi
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  labels:
    app: crapi-web
spec:
  rules:
  - host: crapi-web.9fb2d620bbe449fc880a.southcentralus.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crapi-web
            port:
              number: 80
          
 # ports:
 #  - port: 80
 #    nodePort: 30080
 #  selector:
 #    app: crapi-web
